apiVersion: v1
kind: ReplicationController
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  replicas: 1
  template:
    metadata:
      name: php-apache
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.cn-shenzhen.aliyuncs.com/zogloo/hpa-example 
        resources:
          requests:
            cpu: 20m
        ports:
        - containerPort: 80
