apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - image: tomcat
    name: tomcat
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-log
      mountPath: /usr/local/tomcat/logs
  - image: busybox
    name: busybox
    command: ["sh", "-c", "tail -f /logs/catalina*.log"]
    volumeMounts:
    - name: app-log
      mountPath: /logs
  volumes:
  - name: app-log
    emptyDir: {}
